apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: e-commerce-app
  namespace: argocd
spec: 
  destination: 
    namespace: e-commerce-app
    server: "https://kubernetes.default.svc"
  project: e-commerce-project
  source: 
    path: kubernetes
    repoURL: "https://github.com/mabusaa/argocd-example-apps.git"
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true